import type { RosterFighter } from "./types";

/** The fictional fight card. Everyone here failed something; nobody here is real. */
export const ROSTER: RosterFighter[] = [
  {
    id: "jade-okafor",
    name: "JADE OKAFOR",
    major: "BIOCHEM",
    year: "CLASS OF 27",
    gpa: "2.1",
    record: "14-3",
    failed: "ORGA",
    bio: "Just failed Organic Chem. Not talking about it. Punching about it.",
    tone: "flame",
    swipeBackChance: 0.35,
  },
  {
    id: "kofi-mensah",
    name: "KOFI MENSAH",
    major: "MECH ENG",
    year: "CLASS OF 26",
    gpa: "3.1",
    record: "1-2",
    failed: "THERMO",
    bio: "Entropy is chaos. So am I after an F. Loser buys dining hall nuggets.",
    tone: "match",
    swipeBackChance: 0.7,
  },
  {
    id: "mara-voss",
    name: "MARA VOSS",
    major: "MOLECULAR BIO",
    year: "CLASS OF 28",
    gpa: "3.7",
    record: "4-0",
    failed: "OCHEM",
    bio: "Undefeated, unbothered, extremely well-rested. Gym opens 6am.",
    tone: "blood",
    swipeBackChance: 0.2,
  },
  {
    id: "theo-park",
    name: "THEO PARK",
    major: "ECON",
    year: "CLASS OF 27",
    gpa: "2.4",
    record: "6-6",
    failed: "STATS 2",
    bio: "My p-value is significant and so is my left hook.",
    tone: "cream",
    swipeBackChance: 0.6,
  },
  {
    id: "priya-nair",
    name: "PRIYA NAIR",
    major: "COMP SCI",
    year: "CLASS OF 26",
    gpa: "3.4",
    record: "9-1",
    failed: "ALGORITHMS",
    bio: "Failed a dynamic programming exam. Now optimizing for violence.",
    tone: "flame",
    swipeBackChance: 0.3,
  },
  {
    id: "diego-alvarez",
    name: "DIEGO ALVAREZ",
    major: "ARCHITECTURE",
    year: "GRAD STUDENT",
    gpa: "2.9",
    record: "3-5",
    failed: "STRUCTURES",
    bio: "My bridge collapsed in the final. Let's see if you do.",
    tone: "match",
    swipeBackChance: 0.75,
  },
  {
    id: "hana-sato",
    name: "HANA SATO",
    major: "PRE-MED",
    year: "CLASS OF 28",
    gpa: "3.9",
    record: "12-0",
    failed: "PHYSICS 1",
    bio: "One B-minus and I snapped. Light rounds only. Kidding.",
    tone: "blood",
    swipeBackChance: 0.15,
  },
  {
    id: "marcus-bell",
    name: "MARCUS BELL",
    major: "FINANCE",
    year: "CLASS OF 26",
    gpa: "2.0",
    record: "0-7",
    failed: "ACCOUNTING",
    bio: "Zero wins, zero fear. Debits on the left, fists on the right.",
    tone: "cream",
    swipeBackChance: 0.9,
  },
  {
    id: "ines-ferreira",
    name: "INES FERREIRA",
    major: "PHILOSOPHY",
    year: "CLASS OF 27",
    gpa: "3.2",
    record: "5-2",
    failed: "FORMAL LOGIC",
    bio: "If I lose, did I really lose? Yes. Which is why I won't.",
    tone: "flame",
    swipeBackChance: 0.5,
  },
  {
    id: "sam-whitaker",
    name: "SAM WHITAKER",
    major: "ENGLISH",
    year: "CLASS OF 29",
    gpa: "2.6",
    record: "2-2",
    failed: "LINGUISTICS",
    bio: "Wrote a 12-page essay on why I'll beat you. Got a C on it.",
    tone: "match",
    swipeBackChance: 0.65,
  },
  {
    id: "lena-kowalski",
    name: "LENA KOWALSKI",
    major: "CHEM ENG",
    year: "CLASS OF 26",
    gpa: "2.3",
    record: "8-4",
    failed: "FLUIDS",
    bio: "Reynolds number of my rage: extremely turbulent.",
    tone: "blood",
    swipeBackChance: 0.4,
  },
  {
    id: "omar-haddad",
    name: "OMAR HADDAD",
    major: "MATH",
    year: "GRAD STUDENT",
    gpa: "3.0",
    record: "7-3",
    failed: "REAL ANALYSIS",
    bio: "Proved I can fail by induction. Base case: this semester.",
    tone: "cream",
    swipeBackChance: 0.55,
  },
];

export const ROSTER_BY_ID: Record<string, RosterFighter> = Object.fromEntries(
  ROSTER.map((f) => [f.id, f]),
);
